#!/bin/bash
# machine-env.sh — resolves machine-specific values for the test suite.
# Source this; do not execute.
#
# Values persist to .claude/test-machine.env (gitignored — .claude/ is machine-local
# by repo convention). First run derives everything and writes the file; edit it to
# override on machines where detection guesses wrong. Delete it to re-derive.
#
#   TEST_PY           functional python (python3 -> python -> py, real probe)
#   TEST_CLI_VERSION  `claude --version` on this machine
#   TEST_WORKER_PORT  claude-mem worker port (~/.claude-mem/settings.json, default 37777)
#   TEST_PLATFORM     uname -s

TESTS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$TESTS_DIR/.." && pwd)
MACHINE_ENV_FILE="$REPO_ROOT/.claude/test-machine.env"

[ -f "$MACHINE_ENV_FILE" ] && . "$MACHINE_ENV_FILE"

if [ -z "${TEST_PY:-}" ]; then
    for c in python3 python py; do
        if "$c" -c "pass" >/dev/null 2>&1; then TEST_PY="$c"; break; fi
    done
fi
[ -n "${TEST_PY:-}" ] || { echo "[machine-env] FAIL: no working python (python3/python/py)"; return 1 2>/dev/null || exit 1; }

if [ -z "${TEST_CLI_VERSION:-}" ]; then
    TEST_CLI_VERSION=$(claude --version 2>/dev/null | head -1 | awk '{print $1}')
    TEST_CLI_VERSION="${TEST_CLI_VERSION:-unknown}"
fi

if [ -z "${TEST_WORKER_PORT:-}" ]; then
    TEST_WORKER_PORT=$("$TEST_PY" -c "
import json, os
try:
    print(json.load(open(os.path.expanduser('~/.claude-mem/settings.json'))).get('CLAUDE_MEM_WORKER_PORT', '37777'))
except Exception:
    print('37777')
" 2>/dev/null)
fi

TEST_PLATFORM="${TEST_PLATFORM:-$(uname -s 2>/dev/null || echo unknown)}"

if [ ! -f "$MACHINE_ENV_FILE" ]; then
    mkdir -p "$REPO_ROOT/.claude"
    cat > "$MACHINE_ENV_FILE" <<EOF
# test-machine.env — machine-specific values for tests/ (auto-generated by
# tests/machine-env.sh; edit to override, delete to re-derive). Gitignored.
TEST_PY="$TEST_PY"
TEST_CLI_VERSION="$TEST_CLI_VERSION"
TEST_WORKER_PORT="$TEST_WORKER_PORT"
TEST_PLATFORM="$TEST_PLATFORM"
EOF
fi

export TEST_PY TEST_CLI_VERSION TEST_WORKER_PORT TEST_PLATFORM
